### ISSUE TITLE
Tensorflow installation tutorial code overwrites .bashrc

### ISSUE THREAD

**Issue by mvinoba** [ericdaat/ericdaat.github.io#1]
Thanks for the blog post, it helped me a lot. However, the following lines on `Installing Cudnn
` session overwrites (`>`) `.bashrc` instead of appending to it (`>>`), which is what I think you meant to recommend. 
```bash
echo "export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64"" > .bashrc
echo "export CUDA_HOME=/usr/local/cuda" > .bashrc
```
on lines https://github.com/ericdaat/ericdaat.github.io/blob/f9e8387b3b9026a954cbe768b581f171c5a23866/install-tensorflow-gpu.html#L87-L88

**Comment by ericdaat** [comment]
Hi Vinicius,

Oh you are right, thanks a lot for bringing this up ! I fixed these two lines, it should appear on the blog anytime soon !
I'm glad the post was helpful 😃 

Best,
Eric
